name: Add Action
on: [push]
jobs:
  Cypress-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout GitCode
        uses: actions/checkout@v2

      - name: Run Cypress Test
        uses: cypress-io/github-action@v4
        with:
          start: npm start
          command: npx cypress run
          
